### ISSUE TITLE
Error message 'The system cannot find the file specified.'

### ISSUE THREAD

**Issue by IwanParf** [brucelab/xlinkprophet#1]
Dear developers of Xlinkprophet,
I was trying to run Xlinkprophet on Win10 with Strawberry Perl 64-bit 5.42.0.1 within the Windows PowerShell with the provided Mango test data and got the following error message: 
    **The system cannot find the file specified.
   Problem greping grep '<mod_aminoacid_mass' E:\Xlinkprophet\Mango_test_set/interact.pep.xml | grep -c variable**

Same error with the iprophet.pep.xml.
First, I thought it is a slash backslash problem in case the program was written on a Linux OS, but changing "/" to "\\" in line 102 of XLinkProphet.pl led to the same error message but with the correct path:
   **The system cannot find the file specified.
   Problem greping grep '<mod_aminoacid_mass' E:\Xlinkprophet\Mango_test_set\interact.pep.xml | grep -c variable**

Interestingly, when I comment out this part of the code that leads to the error (line 213 to 225) and define $REMOVE_STATIC_MODS as 1, it of course still crashes, but it is reading in the pep.xml:
   **Using CROSSLINKMODS: K:325.13,n:198.04
   Pairing Algorithm: Mango
   Warning: using scan directory E:\Xlinkprophet\Mango_test_set/ since not found in E:\Xlinkprophet\Mango_test_set \.\interact.pep.xml name
   Parsing pepXML file E:\Xlinkprophet\Mango_test_set\.\interact.pep.xml
   Read in results for 82796 spectra** [...]

Meaning that it actually finds the input pep.xml. I am out of my wits, since my perl intro course was 6 years ago. Is there an obvious mistake that I am doing?

Best,

Iwan

**Comment by brucelab** [comment]
Dear Iwan,

I updated both runXLinkProphet.pl and XLinkProphet.pl with versions that will hopefully run on Windows machines.  Please download these new program versions and let me know if they work for you.

Andrew

**Comment by IwanParf** [comment]
Dear Andrew,
It is working now, thank you very much! 

Cheers,

Iwan
